title: Markus Käser
subtitle: Echter Neuanfang von unten.
email: kaeserwaehlen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Echter Neuanfang von unten.
keywords: SPD, Bayern, Käser, Markus, Politik, Landesvorsitzender

baseurl: ""
assets_base_url: "assets/"

markdown: kramdown
source: src
destination: dist

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - webpack.config.js
  - Procfile.development
  - npm-debug.log
  - node_modules
  - bin
